version: '2'
services:
  web:
    container_name: web
    build:
      context: web
    volumes:
      - ./web/dist:/usr/share/nginx/html
    ports:
      - "8000:80"
  backend-go:
    container_name: backend-go
    build:
      context: backend-go
    expose:
      - "9091"
  backend-node:
    container_name: backend-node
    build:
      context: backend-node
    volumes:
      - ./proto:/proto
    expose:
      - "9092"
  proxy:
    container_name: proxy
    build:
      context: proxy
    volumes:
      - ./proxy/config.yaml:/etc/envoy/config.yaml
    ports:
      - "9090:9090"
    links:
      - web
      - backend-go
      - backend-node
